apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ./admin-access.yaml
- ./olm.yaml

# - service-mesh.yaml
# - kubernetes-dashboard.yaml
# - prometheus-operator.yaml
# #- vault-operator.yaml
# - logging-operator.yaml
# - logging.yaml
# - eck.yaml
# #- vault.yaml

# #- guestbook.yaml



