apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

#
# Ordered list of application manifests to install
#
resources:
  - systems/admin-access/application.yaml
  - systems/olm/application.yaml
  # - systems/prometheus-operator/application.yaml
  # - systems/kubernetes-dashboard.yaml 
  # - app-manifests/service-mesh.yaml
  # - app-manifests/elastic-operator.yaml

  # - systems/vault/vault-operator.yaml

# - logging-operator.yaml
# - logging.yaml

# #- vault.yaml

# #- guestbook.yaml



