---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

#
# Ordered list of application manifests to install
#
resources:
 - stacks/admin.yaml
 - stacks/goodies.yaml  
  # - stacks/devops.yaml
 - stacks/infrastructure.yaml
  # - stacks/observability.yaml
 - stacks/aws.yaml


#   - systems/service-mesh/application.yaml
#   - systems/olm/application.yaml
# #  - systems/prometheus-operator/application.yaml
#   - systems/kubernetes-dashboard/application.yaml 
#   # - systems/elastic-operator/application.yaml   
# #  - systems/vault-operator/application.yaml
#   - systems/weavescope/application.yaml

#   - systems/pulsar/application.yaml

