apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

#
# Ordered list of application manifests to install
#
resources:
  - vault-mysql.yaml
  - vault-backed-by-mysql.yaml
  - vault-secrets-webhook.yaml
