---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-webhook
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'http://kubernetes-charts.banzaicloud.com/branch/master'
    targetRevision:  0.7.0
    chart: vault-secrets-webhook

    helm:
      values: |
   
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

