apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: logging
  name: logging

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-operator
  namespace: argocd

spec:
  project: default
  source:
    repoURL: http://kubernetes-charts.banzaicloud.com/branch/master
    targetRevision:  2.7.2
    chart: logging-operator

    helm:
      values: |

        # Fluent-bit configurations
        fluentbit: {}

        # Fluentd configurations
        fluentd: {}

        # Limit namespaces from where to read Flow and Output specs
        watchNamespaces: []

        # Control namespace that contains ClusterOutput and ClusterFlow resources
        controlNamespace: logging


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

