---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: logs-kibana
  namespace: logging
spec:
  targetNamespace: logging
  version: 7.5.1
  count: 1
  elasticsearchRef:
    name: logs-db

# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   name: kibana
#   namespace: logging
#   annotations:
#     fluxcd.io/automated: "true"
#     fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
# spec:
#   releaseName: kibana
#   chart:
#     repository: https://helm.elastic.co
#     name: kibana
#     version: 7.5.1

#   values:

#     elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"
#     protocol: http