apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: quickstart-kibana
  namespace: logging
spec:
  targetNamespace: logging
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: quickstart-es