---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
  namespace: vault
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: vault-secrets-webhook
  chart:
    repository: http://kubernetes-charts.banzaicloud.com/branch/master
    name: vault-secrets-webhook
    version: 0.7.0
