apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: pulsar
  name: pulsar

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/apache/pulsar/
    targetRevision: HEAD
    path: deployment/kubernetes/helm/examples/k8s

    # targetRevision:  1.0.0
    # chart: pulsar

    helm:
      values: |
        


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pulsar

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

