---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: confluent-operator
  namespace: confluent-operator
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: confluent-operator
  chart:
    git: https://github.com/robparrott/k8s-gitops.git
    ref: master
    path: charts/confluent-operator

  values:

    serviceAccounts:
     
      ## Confluent Operator requires cluster-level admin access
      operator:
        name: cc-operator

    ## 
    ## Overriding values for Chart's values.yaml for AWS
    ##
    ## This is the content of "providers/aws.yaml"
    ##
    global:
      provider:
        name: aws
        region: us-east-2
        kubernetes:
           deployment:
             ## If kubernetes is deployed in multi zone mode then specify availability-zones as appropriate
             ## If kubernetes is deployed in single availability zone then specify appropriate values
             zones:
              - us-east-2a
              - us-east-2b
              - us-east-2c
        storage:
          provisioner: kubernetes.io/aws-ebs
          ## Use Retain if you want to persist data after CP cluster has been uninstalled
          reclaimPolicy: Delete
          parameters:
            encrypted: "true"
            kmsKeyId: ""
            type: gp2
        ## Docker registry endpoint where Confluent Images are available.
        ##
        registry:
          fqdn: docker.io
          credential:
            required: false

          # fqdn:
          # credential:
          #   ## Enable if authentication is required to pull images in kubernetes cluster.
          #   ##
          #   required: false
          #   ## Docker login username
          #   ##
          #   username: ""
          #   ## Docker login password
          #   ##
          #   password: ""
       
      # pod:
      #   securityContext:
      #     fsGroup: 1001
      #     runAsUser: 1001
      #     runAsGroup: ""
      #     runAsNonRoot: true
      #     supplementalGroups: []
      #     seLinuxOptions: {}

      sasl:
        plain:
          username: test
          password: test123

      ##
      ## Init Container configurations
      ##
      initContainer:
        image:
          repository: confluentinc/cp-init-container-operator
          tag: 5.4.0.0


    ##      
    ## Operator
    ##
    operator:
      enabled: true
