---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
  # annotations:
  #   fluxcd.io/automated: "true"
  #   fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: fluentd
  targetNamespace: logging
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: fluentd
    version: 2.3.2

  values:

    output:
      host: elasticsearch-master.logging.svc.cluster.local
      port: 9200
      scheme: http
      sslVersion: TLSv1
      buffer_chunk_limit: 2M
      buffer_queue_limit: 8


    # Enable autoscaling using HorizontalPodAutoscaler
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 5
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 60
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 60

    terminationGracePeriodSeconds: 30