---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: kibana
  chart:
    repository: https://helm.elastic.co
    name: kibana
    version: 7.5.1

  values:

    protocol: http