---
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:

  size: 2
  image: 'vault:1.2.3'
  bankVaultsImage: 'banzaicloud/bank-vaults:latest'

  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9102'

  serviceAccount: vault
  serviceType: ClusterIP
  ingress:
    annotations: null
    spec: {}

  unsealConfig:
    kubernetes:
      secretNamespace: default

  config:
    storage:
      file:
        path: /vault/file
    listener:
      tcp:
        address: '0.0.0.0:8200'
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    telemetry:
      statsd_address: 'localhost:9125'
    ui: true
    
  externalConfig:
    policies:
      - name: allow_secrets
        rules: >-
          path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            policies: allow_secrets
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
    # startupSecrets:
    #   - type: kv
    #     path: secret/data/accounts/aws
    #     data:
    #       data:
    #         AWS_ACCESS_KEY_ID: secretId
    #         AWS_SECRET_ACCESS_KEY: s3cr3t
  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug

# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   name: vault
#   namespace: vault
#   annotations:
#     fluxcd.io/automated: "true"
#     fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
# spec:
#   releaseName: vault
#   chart:
#     repository: https://kubernetes-charts.banzaicloud.com
#     name: vault
#     version: 0.10.0

#   values:

#     image:
#       repository: vault
#       tag: 1.2.3
#       pullPolicy: IfNotPresent

#     vault:
#       config:
#         file:
#           path: "/vault/file"
#         # storage:
#         #   consul:
#         #     address: "myconsul-svc-name:8500"
#         #     path: "vault"


