# apiVersion: v1
# kind: Namespace
# metadata:
#   name: vault
# ---
# apiVersion: operators.coreos.com/v1alpha2
# kind: OperatorGroup
# metadata:
#   name: operatorgroup
#   namespace: vault
# spec:
#   targetNamespaces:
#   - vault
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: vault
#   namespace: vault
# spec:
#   channel: beta
#   name: vault
#   source: operatorhubio-catalog
#   sourceNamespace: olm

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: vault-operator
  chart:
    repository: http://kubernetes-charts.banzaicloud.com/branch/master
    name: vault-operator
    version: 0.2.17

  values:

    replicaCount: 3

    # etcd-operator:
    #   enabled: true
    #   etcdOperator:
    #     commandArgs:
    #       cluster-wide: true
