---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh
  namespace: argocd

  finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
    - resources-finalizer.argocd.argoproj.io 
      
spec:
  project: default
  source:
    repoURL: https://github.com/parrottr/k8s-gitops.git
    targetRevision: HEAD
    path: systems/service-mesh
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

